AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tensorflow-inference-docker-lambda

  SAM Template for tensorflow-inference-docker-lambda

Resources:
  TensorFlowInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 1800
      Timeout: 120
      EphemeralStorage:
        Size: 1024
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  TensorFlowInferenceFunction:
    Description: "TensorFlowInference Lambda Function ARN"
    Value: !GetAtt TensorFlowInferenceFunction.Arn
  TensorFlowInferenceFunctionIamRole:
    Description: "Implicit IAM Role created for TensorFlowInference function"
    Value: !GetAtt TensorFlowInferenceFunction.Arn
